
#General Settings
[general]
	#Multiply the speed at which you change temperature.
	#Range: 0.0 ~ 1.7976931348623157E308
	baseSpeedModifier = 1.0

#Serene Seasons Compatibility
[seasons]
	#Serene Seasons spring modifier.
	#Range: -99999.0 ~ 99999.0
	seasonSpringMod = 10.0
	#Serene Seasons summer modifier.
	#Range: -99999.0 ~ 99999.0
	seasonSummerMod = 20.0
	#Serene Seasons autumn modifier.
	#Range: -99999.0 ~ 99999.0
	seasonAutumnMod = -10.0
	#Serene Seasons winter modifier.
	#Range: -99999.0 ~ 99999.0
	seasonWinterMod = -20.0

